### ISSUE TITLE
zone.current is undefined for cluster mode

### ISSUE THREAD

**Issue by nikolay-rogovoy** [JsCommunity/node-zone#3]
```
            // test 2 - Failed: current is undefined <---
            zone.current.fork({
                name: 'api',
                properties: {
                    id: 2
                }
```

Full version:
https://github.com/nikolay-rogovoy/test_js/blob/master/src/main_2.js

Steps to reproduce:
1) git clone https://github.com/nikolay-rogovoy/test_js.git
2) cd test_js
3) npm i
4) npm run main_2
5) send http request: get http://localhost:8000/api/test
6) test 2 - Failed

Proposed Solution:
`index.js` :

```
  before(uid) {
    if (zones[uid]) {
      current = zones[uid];
    } else {
      zones[uid] = current;
    }
  },
```

**Comment by julien-f** [comment]
Thank you for your report, I'll take a look as soon as I can.

In the meantime, a PR with unit test for this issue (and possibly a fix) would be most welcome :wink:

**Comment by julien-f** [comment]
It appears the `init` hook is not called in workers when a callback is added to the `request` event of the server, therefore it's not possible to save the current zone.

When the callback is called, the `before` event is properly called but there is no zone saved for it so it cannot be restored.

I have no idea how to fix this issue.

@AndreasMadsen any inputs on this?

**Comment by nikolay-rogovoy** [comment]
Thank you, this is bug nodejs.
When do you publish this on npm?

**Comment by julien-f** [comment]
@nikolay-rogovoy Have you tried the PR?

I'm reluctant because this work-around is not transparent, it changes the behavior in this case: instead of using the current zone it will use the root zone:

```js
Zone.current.fork('foo').run(() => {
  http.createServer((req, res) => {
    // should be 'foo' but will be '<root>' in a cluster child
    console.log(Zone.current.name)
  }).listen(80)
})

**Comment by nikolay-rogovoy** [comment]
Controller handlers are usually fine.
This does not happen often.
But if this is not done, then zones cannot be used in the cluster.
Can make a fork with this fix?

**Comment by julien-f** [comment]
> But if this is not done, then zones cannot be used in the cluster.

You're right, I'll make a release.

**Comment by nikolay-rogovoy** [comment]
Thank you!
